apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: application
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend
